export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const FETCH_CARPLATE = 'FETCH_CARPLATE';
export const FETCH_POSTCODE = 'FETCH_POSTCODE';
export const FETCH_FIATEXCHANGE = 'FETCH_FIATEXCHANGE';
export const FETCH_CRYPTOVALUE = 'FETCH_CRYPTOVALUE';